### ISSUE TITLE
Images all displaying as broken.

### ISSUE THREAD

**Issue by princessGasmask** [infinity-next/infinity-next#102]
http://puu.sh/jsAat/32011f499d.png
Just installed and decided to play around with creating/destroying boards. Everything else works fine except for the fact that all posts uploaded have broken images. Is the board pointing at the wrong directory for the images, or is the folder simply not created?

**Comment by jaw-sh** [comment]
Inspect the element and get the URL for the image, show me what it is. 
Attempt to open it in your browser. You may get a proper error page.

If you're not using a host name (i.e. you're accessing it through 
127.0.0.1 instead of infnext.foo), I am aware that an issue with that 
exists already.

**Comment by princessGasmask** [comment]
Ah, okay. Yes, I was testing it using localhost:portname.

**Comment by jaw-sh** [comment]
Does setting a hostname resolve the issue?

**Comment by princessGasmask** [comment]
Actually new to using Laragon as opposed to XAMPP, so I'll play around with it and report back.

**Comment by princessGasmask** [comment]
Apparently, I'm stupid and don't remember how to actually do this.

**Comment by princessGasmask** [comment]
After dicking about for a while, I figured it out. Thanks for the push in the right direction.
