### ISSUE TITLE
Possible security issues with sessions

### ISSUE THREAD

**Issue by spanishtech** [infinity-next/infinity-next#104]
So I haven't looked into how sessions are kept in laravel or this project.

Here it goes:
1. Log in
2. Post something
3. Open new incognito
4. You can edit that post with incognito session

I'm assuming this is caused because both have the same IP (and maybe UUID, if that is used to help identify). If cloudflare is used you can spoof IPs.

Again I haven't spent much time looking into this, I just noticed it and thought you should know

**Comment by jaw-sh** [comment]
You shouldn't be able to edit your own post at all without an account. 
Is this on a clean install? The default permissions may be a bit off if 
that's the case.

But yes, it works via IP and is insecure as a result. We'll be changing 
this to a password at some point.

**Comment by spanishtech** [comment]
It was with an account.
I wasn't sure if you where aware but that should be all good then. Thanks for notifying me.
