### ISSUE TITLE
404 failure

### ISSUE THREAD

**Issue by spanishtech** [infinity-next/infinity-next#110]
So I noticed when updated (Which I hadn't done in a while) there where numerous errors (first being a captcha but I assume that was me)
The one I assume is just a small thing that you can fix is that thread is not checked to be null before calling it's setRelation() method on line 459 of Board.php

## Error here
```php
			$thread = $this->posts()
				->where('board_id', $board_id)
				->withEverythingAndReplies()
				->orderBy('bumped_last', 'desc')
				->get()
				->first();

			$thread->setRelation('board', $this);

```
## Proposed fix
```php
			if(!$thread)
			{
				return $thread;
			}
			$thread->setRelation('board', $this);
```
This does fix the issue but I'm unsure if it's up to scratch with standards

**Comment by jaw-sh** [comment]
The captcha issue is going to be because we moved to a remote Captcha repository. Run `composer update`.

Your assessment was 100% correct. I just went with a more pedantic way of doing things.

```
if ($thread instanceof Post)
```

**Comment by spanishtech** [comment]
I'm reluctant with updating as I'm currently spending a lot of time modifying the software and updating requires a lot of effort to merge it.

I'm actually about to switch out for recaptcha so I probably wont bother yet.
Thanks though,

**Comment by jaw-sh** [comment]
If you're planning an upstream commit I would implore you to discuss changes with me first.

**Comment by spanishtech** [comment]
Not planning on bothering to commit these changes. They're mainly personal, things like making identification of authors based on author_id and author_id including a 3 day cookie value.
