### ISSUE TITLE
Support video/ogg and audio/ogg

### ISSUE THREAD

**Issue by jaw-sh** [infinity-next/infinity-next#119]
Because it's free as in freedom.

**Comment by ctrlcctrlv** [comment]
Opus too right? You closed this without attaching a commit...

**Comment by ctrlcctrlv** [comment]
List of free as in freedom media codecs supported in browsers:

Video:
VP8 (webm)
VP9 (webm)
libtheora (ogg)

Audio:
vorbis (ogg)
opus (ogg)

**Comment by jaw-sh** [comment]
Everything you've mentioned is supported.

See: https://github.com/infinity-next/sleuth
