### ISSUE TITLE
Issues getting Next to work with GD

### ISSUE THREAD

**Issue by milezteg** [infinity-next/infinity-next#120]
Got this running today and all is well but the sexy captcha by brennan.  I found the config in /config/captcha.php - didn't change anything there.

The captcha is not showing and when I right click on where the image supposed to be it shows:  `/cp/captcha/default/8cb4cbf91262f58b88fb3d512dbd699021f62752.png`.  That seems okay except that path did not exist so I created it with write permissions.  Didn't change anything.

From my nginx log:

`2015/09/05 06:19:04 [error] 24141#0: *474 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function InfinityNext\BrennanCaptcha\imageantialias() in /var/www/domain.com/vendor/infinity-next/brennan-captcha/src/Captcha.php on line 233" while reading response header from upstream, client: 24.xx.xx.xx, server: domain.com, request: "GET /cp/captcha/default/5f24249dee3370321679d774217b2c88aa1bd8ae.png HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "domain.com", referrer: "http://domain.com/test/catalog"`

Has anyone run across this with a fresh install of latest code?

**Comment by jaw-sh** [comment]
Okay, so first: No request will have a physical file. All requests work like this:

/cp/captcha/default/xxxxxxxxxxxxxxxxxxxxxx.png ->
/public/index.php?/cp/captcha/default/xxxxxxxxxxxxxxxxxxxxxx.png

So you do not need to create anything ever. The error here is a script error.

```
PHP message: PHP Fatal error: Call to undefined function InfinityNext\BrennanCaptcha\imageantialias() in /var/www/domain.com/vendor/infinity-next/brennan-captcha/src/Captcha.php on line 233
```

You're missing this.
http://php.net/manual/en/function.imageantialias.php

Which should be available for PHP 4 >= 4.3.2, PHP 5, PHP 7

Can you please access /cp/site/phpinfo and tell me what version (big black text up at the top by the logo) you're running? If the verison is above 4.3.2 (which it damn well should be lol), then CTRL+F and paste this in on the same page.

```
GD Version
```

You should find something that looks like this:
![](http://i.imgur.com/t1JNoAK.png)

**Comment by milezteg** [comment]
**PHP Version 5.6.13-0+deb8u1**
**GD Version:  2.1.1-dev**

Ahaaa, yes that makes sense!  Looks like I have to recompile PHP-fpm :(

Just to confirm I am missing the function:

`# php -r "var_dump(function_exists('imageantialias'));"
bool(false)`

I read through this:  https://bugs.launchpad.net/ubuntu/+source/php5/+bug/74647

I am running Debian 8.1 Jessie and these sources:

`deb http://ftp.ca.debian.org/debian/ jessie main contrib non-free
deb-src http://ftp.ca.debian.org/debian/ jessie main`

Not 100% sure the best course of action on my distro :/

**Comment by jaw-sh** [comment]
Hummm. That's rough. Those guys responding to the issue are assholes, too. Not sure what you can do about it.

summoning the dark lord @ctrlcctrlv

**Comment by ctrlcctrlv** [comment]
Debian packages GD.

It doesn't work?

https://packages.debian.org/jessie/php5-gd

**Comment by milezteg** [comment]
>>It doesn't work?

Well at least not with Jessie main repos.  Debian so restrictive with what packages allowed in php5.  It's really chasing me away from that distro.  Maintaining a system with this issue doesn't seem like a great idea either.  See here (last post has a cumbersome work around): http://forums.debian.net/viewtopic.php?f=17&t=112195

...I guess I'll rebuild a VM and try again.  which Linux distro are you guys running?

**Comment by jaw-sh** [comment]
Debian. `apt-get install php5-gd` works for me.

**Comment by milezteg** [comment]
>Debian. apt-get install php5-gd works for me.

Yeah that's how I installed it.  So you're using Debian too jaw-sh?  And same repo sources as I posted above?  Hmm wtf.  

I am wondering if maybe the repos at [dotdeb](https://www.dotdeb.org/) might have php5-gd.

**Comment by jaw-sh** [comment]
I didn't custom build my PHP though ...

```
apt-get install php5-fpm
apt-get install php5-gd
```

boom.

**Comment by interjection** [comment]
I've also encountered this issue in both Vivid and Wheezy so far today. @jaw-sh what version are you running where the binaries just werk? So I can reproduce the environment. Maybe package version information as well?

**Comment by milezteg** [comment]
>I didn't custom build my PHP though ...

Neither did I.  I just did apt-get install same as you and Brennan.  Haven't had time to rebuild my VM yet so hope to hear what you discover @interjection

**Comment by jaw-sh** [comment]
@interjection I moved infinitydev.org to a debian 8 My process for installing the software has always been just running apt-gets. The only thing I had to custom compile was FFMPEG for Debian 8 and that was shit but only required if you want webm thumbnails.

```
ii  php5-cli        5.6.13+dfsg- amd64        command-line interpreter for the php
ii  php5-common     5.6.13+dfsg- amd64        Common files for packages built from
ii  php5-curl       5.6.13+dfsg- amd64        CURL module for php5
ii  php5-fpm        5.6.13+dfsg- amd64        server-side, HTML-embedded scripting
ii  php5-gd         5.6.13+dfsg- amd64        GD module for php5
ii  php5-json       1.3.6-1      amd64        JSON module for php5
ii  php5-mcrypt     5.6.13+dfsg- amd64        MCrypt module for php5
ii  php5-memcache   3.0.8-5      amd64        memcache extension module for PHP5
ii  php5-memcached  2.2.0-2      amd64        memcached extension module for PHP5,
ii  php5-mysql      5.6.13+dfsg- amd64        MySQL module for php5
ii  php5-readline   5.6.13+dfsg- amd64        Readline module for php5
```

**Comment by jaw-sh** [comment]
Upon investigating I decided the easiest course of action would be to remove dependency on the antialias function and update the brennan captcha, which is now at v1.1.0.

@milezteg @interjection Please run a Composer update and verify this works.

**Comment by interjection** [comment]
infinity-next/brennan-captcha@1bb445599980a2fec1346b687df31a6f5f68cb2b werks

Also the confusion was that hhvm ships gd functions. Thanks for taking the time, jaw-sh.

**Comment by jaw-sh** [comment]
Nice. Thanks for taking the time to report it.

**Comment by milezteg** [comment]
Just chiming in saying everything works well after rebuilding my VM with Debian 8.2 and pulling latest code without requirement for imageantialias.  Sweet!
