### ISSUE TITLE
Post Delete Issues

### ISSUE THREAD

**Issue by milezteg** [infinity-next/infinity-next#125]
Probably something missed with the permission code....with latest pull from master and the v3 release...

When an admin is deleting posts a simple Delete works but all of these are producing an error:  Delete Board Wide, Ban & Delete, etc.  

`ErrorException in Post.php line 1165: `
`inet_pton(): `

Full stack trace:  http://pastebin.com/X8jAipFY

**Comment by jaw-sh** [comment]
@milezteg Retest please.

**Comment by milezteg** [comment]
Well done =)
