### ISSUE TITLE
UTF8

### ISSUE THREAD

**Issue by spanishtech** [infinity-next/infinity-next#135]
So using UTF8 3 byte and MySQL strict mode, which I believe this application does, causes truncation during insertion.
This may cause issues or may not but it's a good idea not to have this as it could lead to issues later on.
[Explanation of similar issue on wordpress](https://cedricvb.be/post/wordpress-stored-xss-vulnerability-4-1-2/)
That explains the basic premise of the issue.
It's defiantly not a major issue as stated, but it can lead to stored XSS later on.

**Comment by jaw-sh** [comment]
I need an exact case to replicate this issue.

**Comment by spanishtech** [comment]
Use this string anywhere in the application ex𝌆tic
and truncation will occur.

**Comment by jaw-sh** [comment]
You know more about this than I do. What is the ideal solution? Is it an issue with infinitydev's MariaDB setup or is there something in the codebase that needs to be modified?

**Comment by spanishtech** [comment]
Either switching to utf8mb4 or latin1 or disabling strict SQL mode

**Comment by jaw-sh** [comment]
>disabling strict SQL mode
Does this have any adverse affects?

**Comment by spanishtech** [comment]
It stops validation of data before being inserted.
So Strict mode sees the 𝌆 character and since it's not valid for utf8 and as such truncates the string at that point

**Comment by jaw-sh** [comment]
I've modified the MySQL driver to use utf8mb4 like you've suggested. It appears to work.

**Comment by rajlaksh** [comment]
Default MySql Charset is UTF8. UTF8MB4 for emoji :smile:

**Comment by ctrlcctrlv** [comment]
Yes, utf8mb4 is best on MySQL...8chan uses the same. Just another "feature" of MySQL. :wink:

**Comment by rajlaksh** [comment]
utf8mb4 for emoji support that introduce in Mysql 5.5.x :smile:
