### ISSUE TITLE
HTML5 Audio player is too small.

### ISSUE THREAD

**Issue by mixedCase** [infinity-next/infinity-next#136]
Title. This makes changing volume from the player nigh impossible, speaking at least of Chromium's.

I couldn't make sense of the codebase or I'd have submitted a PR :/

**Comment by spanishtech** [comment]
I saw this researching alternative layouts that could replace native players and a modified version of this could be space efficient for small spaces
![Thing](http://puu.sh/kDDwO/81f9201424.jpg)
[Where I found it](http://jplayer.org/)
This may be a great alternative for replacing the native players later on. Although I haven't bothered to check it out fully.

**Comment by mixedCase** [comment]
@spanishtech That includes no volume slider and eschews the HTML5 player for more JS bloat, which would be undesirable.

Simply making the audio player 30-50% larger would solve the issue.

**Comment by spanishtech** [comment]
Personally I like and prefer to have a small little dedicated player with decent controls dedicated to the sizes this will be viewed in. I think it'd be cool.

But since that does solve the issue more effectively then creating a new layout for controlling audio , ignore my idea and pretend I wasn't going over the top.

P.S. I meant add a volume slider when i said modified. But DW. Twas a silly idea.

**Comment by jaw-sh** [comment]
Planned as a part of Milestone 7. I want something like this:

![answer](https://cloud.githubusercontent.com/assets/9262991/10399634/5fd8a130-6ee6-11e5-9b4b-ac7e5ecc2be1.png)

**Comment by jaw-sh** [comment]
Patch 7be4db7206bb829249ffa08c1e5d4c56947b3515 attempts to resolve this if I can't get the proper player in in time.

**Comment by mixedCase** [comment]
If you don't mind Josh, I'll close this issue since your soundcloud-like player work is unrelated to it. And by the way, great idea, would make /mu/ a much better experience. If I may make a premature recommendation, add a "jump to post" button in the playlist (assuming it'll have one due to the button in that mockup). I've found myself wanting to reply to the post of a webm/song after listening for a bit and that'd be helpful.

And thanks for solving this issue!
