### ISSUE TITLE
Handmade Link :(

### ISSUE THREAD

**Issue by rajlaksh** [infinity-next/infinity-next#137]
Why are you using Handmade Link ?

I need to change every views for pointing correct links.

You should be using **URL::to()** for all link and images :smile:

**Comment by ctrlcctrlv** [comment]
Where are we not doing that? Please link the line number.

**Comment by jaw-sh** [comment]
I need you to be explicit with what is wrong.

1. We should be using url() for every link.
2. If that's not the correct thing to do, what should we be doing?
3. If you're submitting upstream changes, please check with me before writing code so nobody gets frustrated.

**Comment by rajlaksh** [comment]
3-4 Views

**Comment by spanishtech** [comment]
Also I find that URL() doesn't like my SSL and just lists all links as http not https

**Comment by rajlaksh** [comment]
@spanishtech Laravel auto detect HTTPS so it should work.

Are you using any Proxy like Cloudflare?

**Comment by jaw-sh** [comment]
There were two causes here.

1. I was not using `url()` for board URIs in the first month. All board URIs should now be called via `$board->getUrl()`.
2. I was not using `asset()` for public-facing asset URLs.

From your list:
- [x] board.blade.php
- [x] main.blade.php
- [x] error.blade.php
- [ ] pages.blade.php (This doesn't exist in the repository.)
- [x] logo.blade.php

**Comment by rajlaksh** [comment]
Thanks.

pages.blade.php exists in nav folder

**Comment by jaw-sh** [comment]
Ah right on. Thanks mate.
