### ISSUE TITLE
Change hashing for author_id and file_hash

### ISSUE THREAD

**Issue by spanishtech** [infinity-next/infinity-next#143]
You should make hashing definable in the .env
Perhaps like this
```php
Hash(env('APP_HASH'), $toHash);
```
Because md5 is all sorts of aweful and some may like to not use a broken hash.

Author_id should also be full sized but only part is shown and any other field that has a hash shrunken down.

**Comment by jaw-sh** [comment]
md5 is only used for files.

we use bcrypt for passwords.

**Comment by spanishtech** [comment]
You use md5 for the author I'd, and that could be used to identify post owners, like I've suggested before.
Even for files its not the best idea, especially if the site becomes massive.

**Comment by jaw-sh** [comment]
The chance of a collision on author IDs is astronomically low because 
they're only used once per thread. I may upgrade files but I'm still not 
sold. You're talking about odds in the quadrillions.

**Comment by spanishtech** [comment]
I understand that it isn't needed but you should always future proof or at least add the ability for the person usij gthe app to decide.
