### ISSUE TITLE
Every file is executable

### ISSUE THREAD

**Issue by ctrlcctrlv** [infinity-next/infinity-next#147]
@jaw-sh has done `chmod -R 777 *` several times in this repo.

That's unnecessary, and it messes with my terminal, among other things; it's definitely a security problem for every file to be marked executable. Generally only directories should be, and the files inside should be read/write only by their user and perhaps group, and only programs that need to be directly executed by the shell and not an interpreter like PHP should be executable.

I know how to fix this, but I just want to know why it was done in the first place before I do, in case I miss something...

**Comment by jaw-sh** [comment]
cuz I can't edit files in Sublime Text in Windows host OS without it because my Samba user isn't also www-data :---DDD

**Comment by ctrlcctrlv** [comment]
Why not set `o+rw`? I don't think you need `x` (execute) permissions for the other user to use `w` (write). `chmod 666` (on _files only, not directories_) should work fine...
