### ISSUE TITLE
Where is file setting?

### ISSUE THREAD

**Issue by rajlaksh** [infinity-next/infinity-next#148]
I tried to upload a Image it give me error

The files.0 must be between 0 and kilobytes.

I'm uploading jpeg with 500KB filesize

**Comment by jaw-sh** [comment]
Mate you're fucking killing me here.

Open your control panel
Site
Config

Make it any non-zero number.

I cannot take the time to install this application for you.

**Comment by rajlaksh** [comment]
Sorry for causing Trouble.
