### ISSUE TITLE
Vector/CSS Flags

### ISSUE THREAD

**Issue by milezteg** [infinity-next/infinity-next#158]
Not a bug or feature really but I would say a nice UI element if you're designing for mobiles/tablets.  PNGs look so dated on retina displays.  Here's a couple different ones:

http://www.phoca.cz/cssflags/ 
http://lipis.github.io/flag-icon-css/

Something for down the road maybe =)

**Comment by jaw-sh** [comment]
There's no way I can use a 2.1mb repository of flags. It's just not going to happen.

We have a custom repository of flags here https://github.com/infinity-next/flags and a resident flag artist from /vex/ who may be interested in redrawing them at a 32x height for better scaling with DPI, but I can't throw those out for flat SVGs that are larger than the actual bitmap.

**Comment by milezteg** [comment]
Yeap that would would work well too.  Cheers :^)
