### ISSUE TITLE
+50 Pagination not implemented

### ISSUE THREAD

**Issue by jaw-sh** [infinity-next/infinity-next#169]

**Comment by ctrlcctrlv** [comment]
I recommend implementing 2ch format...

Here's some examples

http://qb5.2ch.net/test/read.cgi/operate/1408850375/ whole thread

http://qb5.2ch.net/test/read.cgi/operate/1408850375/l50 OP and last 50 posts
http://qb5.2ch.net/test/read.cgi/operate/1408850375/l2 OP and last 2 posts
http://qb5.2ch.net/test/read.cgi/operate/1408850375/600- OP and all posts from 600 onwards
http://qb5.2ch.net/test/read.cgi/operate/1408850375/10-20 OP and posts ten through twenty
http://qb5.2ch.net/test/read.cgi/operate/1408850375/600 OP and post 600 only
http://qb5.2ch.net/test/read.cgi/operate/1408850375/-100 OP and first 100 posts

**Comment by ctrlcctrlv** [comment]
Apparently there's another letter I didn't know about. I don't really think it's useful so you can implement it or not.

"n"

http://qb5.2ch.net/test/read.cgi/operate/1408850375/n - Whole thread, no OP
http://qb5.2ch.net/test/read.cgi/operate/1408850375/nl50 - last 50 posts only, no OP

**Comment by jaw-sh** [comment]
That's too far a attachment from how the system works. It would be 
really frustrating and time consuming to try and hide OP in a thread so 
I'm just going to skip it.

**Comment by ctrlcctrlv** [comment]
Good idea. Also difficult for JS. Seems like a useless feature anyhow.
