### ISSUE TITLE
Cloudflare JavaScript issues with InstantClick

### ISSUE THREAD

**Issue by milezteg** [infinity-next/infinity-next#173]
Commit:  08c3910a4774c3b763d7b815bd91795109ed04f4

Found these so thought I would document here.  #1 is easy to reproduce but I am only experiencing #2 when using CloudFlare.  Direct IP without going through CF does not reproduce #2.  Dunno why but...

Notes:  minify off, browser cache off, https on.  Just default on CF.

Go to any thread page on infnext and open a js console...

1.  Reproduce by clicking the browse/upload button from any thread page
`TypeError: a is undefined - in /static/vendor/10-jquery/jquery-2.1.4.min.js`

2.  Reproduce by browsing a thread page
`TypeError: script is undefined - in /static/vendor/80-instaclick/instaclick-3.1.0.js line 432`

**Comment by jaw-sh** [comment]
Is this still an issue?

**Comment by milezteg** [comment]
Thanks for fixing my title.  I synched:  bdd7e79d1352a7ab900711d0e2cee1bb0cfb4600

Nice #2 looks fixed on infinitydev.org thread pages, but I can't seem to fix my local copy.  I think I must have some configuration difference.  With the latest commit I don't see it occurring anymore on infintydev.org thread pages but you can still see it happening on some pages like:  https://infinitydev.org/cp/donate - but likely I am getting a CF cached copy.  Anyways...

#1 Same issue, can reproduce on infinitydev.org.

#2 Fixed on infinitydev.org.  Can't fix it in my own repo. Just to iterate a bit...I go to a thread page, see the error, refresh the page and the error is suppressed.  Weird. And Instaclick works fine without CF (straight to https://IP).  I must have some difference in my setup somewhere.

I am doing `php artisan cache:clear` and clearing memcached after commits as well as leaving Cloudflare in dev mode.  Browser set to not use cache.  Set both of these to *file* from *memcached*, same thing:  `CACHE_DRIVER=file, SESSION_DRIVER=file`.  No idea what is tripping up CF.

**Comment by milezteg** [comment]
#2 I solved but I am not 100% sure enough what fixed it to document here.  No more instantclick errors.  It had to do with cloudflare settings and non-www domains.  Really unimpressed with cloudflare because reasons but I won't rant here.

#1 I think you know about and is likely an order issue with some javascript loading.  Doesn't effect the website functioning anyways.

Closing this one.
