### ISSUE TITLE
Add WebP support

### ISSUE THREAD

**Issue by TUSF** [infinity-next/infinity-next#180]
WebP is an image format Google is developing.
When compared to PNG and JPEG, WebP is superior, being able to cut off from a quarter to half of an image's size, while maintaining the quality (if compressed properly)

For browsers that do not support WebP (namely Firefox and IE/Edge), you can instead fallback onto PNG and JPEG files (though this is only viable if you only use WebP for static files; unless you think your server can handle converting uploaded files on the fly, and hold copies of both versions). There is also [a Javascript implementation of the WebP Decoder](http://webpjs.appspot.com/) (though it seems to be out-dated? Probably won't support newer features)

This is just a well-meaning idea that if implemented properly, could potentially cut down on a significant amount of bandwidth.

Or it might just add bloat and strain to the server; who knows?

**Comment by jaw-sh** [comment]
I'm wary of doing this because, as you've said, it is not widely supported yet. I will be happy to add it once it is more well supported by browsers.

**Comment by TUSF** [comment]
Even if you want want users to upload WebP images, they can still be used for static images, where if a browser her "image/webp" in their "Accept" header, you serve the WebP image, and otherwise you fallback onto static PNG and JPEG images.

This can be done for icons, banners, and even thumbnails could reasonably be generated in both JPEG and WebP format, and served to users alternatively, depending on their browser/headers.
