### ISSUE TITLE
The Navigation Bar at Bottom should be at Top

### ISSUE THREAD

**Issue by GodOfConquest** [infinity-next/infinity-next#182]
First of all, WOW.
I'm impressed. This is the greatest Imageboard software i have seen till now. Congratulations. Keep doing the good work. I might even start an imageboard website from your software. I will make sure to keep in contact with you. <3

Secondly, As i said in my subject, The Navigation Bar at the Bottom should be at Top because it is the  trademark for all the imageboards around the world and also its a big mess to scroll down till bottom to navigate there. See reddit even they look the subreddit and poplular reddit styling from imageboards like 4chan.

**Comment by jaw-sh** [comment]
You can edit the templates to achieve this very easily. In fact, the 
bottom nav is present but hidden at the top so it's achievable with CSS. 
The link sprawl is defunct in Infinity configurations because there are 
too many boards for the sprawl to work as intended.
