### ISSUE TITLE
is this legit?

### ISSUE THREAD

**Issue by quetea** [infinity-next/infinity-next#185]
i hate to open a non-technical issue, but this post has been making its rounds, and it would be nice if we could confirm whether its bullshit or not.
https://medium.com/@josh8chan/why-i-quit-8chan-former-lead-developer-tells-all-e67b3a4891f7#.z3wk8gp1i

i ask here because there appears to be someone named josh who is still making commits, so i assume theyre referring to the same person.

**Comment by jaw-sh** [comment]
Are you for fucking real dude? This is a joke article written 2 moths ago by someone. Why the fuck would I quit and still be committing 5 times a day?
