### ISSUE TITLE
Image attachments

### ISSUE THREAD

**Issue by jaw-sh** [infinity-next/infinity-next#20]
- [x] Add table for storing files.
- [x] Add table for file to post association
- [x] Add form element for uploading images
- [x] Render image inline with post
- [x] Render compressed thumbnails

**Comment by ctrlcctrlv** [comment]
I will work on this since I have nothing better to do today.

[ ] Fileinfo template (dimensions of image, ratio of image, name of file)
[ ] Multiple thumbnailing methods just like Infinity Stable(TM) (gifsicle for animated GIF thumbnails, imagemagick, graphicsmagick, php5-gd)
[ ] ffmpeg/avconv support for WEBM/MP4 ( just like inc/lib/webm/ffmpeg.php )

Some of these need to call `exec()` (and `escapeshellargs()`), don't complain :^)

**Comment by jaw-sh** [comment]
@ctrlcctrlv Anything sophisticated or complex should be done very carefully, or we're going to lay a bad precedent. I said this over IRC but I would strongly suggest looking for Laravel vendors / extensions that automatically handle images. Laravel is the most popular PHP framework and I am absolutely sure this exists.

Any work that requires a library (such as images) should be done through contracts that allow for library agnosticism. Don't ever rely on Imagick because I fucking hate setting it up and it gives me cancer. I'd rather have unanimated thumbnails using gd. If you want to support it for people smart enough to figure it out, that's a plus, but I would say that Infinity Next should not require it to work. Again, look for libraries that already do all this stuff on their own. There's easy ways to add required libraries to composer.

That said, yea, that's all good. I'll probably modify the templates myself after. I have a cool idea for the default theme's way of rendering files. Keep it simple, follow my naming conventions, and don't worry about CSS. I'll do all that.


I did break some stuff with my last change so I'm working on fixing that now. If you have uncommitted work there may be conflicts when I'm done.

**Comment by jaw-sh** [comment]
@ctrlcctrlv We're going to need to improve the getFile controller. I don't know what I did incorrectly but it loads like ass and doesn't cache.

**Comment by jaw-sh** [comment]
I'm marking this complete as the original task is done.
