### ISSUE TITLE
Post widget caches backlinks before they are fully rendered.

### ISSUE THREAD

**Issue by ccd0** [infinity-next/infinity-next#200]
I've noticed that when I hover over a quotelink, the post shown is sometimes missing or incomplete.  I think this is due to the `MutationObserver` callback binding widgets for which the start tag has been loaded and parsed, but not all the children have been inserted yet.

To confirm I used a proxy to inject

    var lastElement = document.getElementById('page-container');
    if (document.readyState === 'loading' && lastElement) {
    	while (lastElement.lastElementChild) {
    		lastElement = lastElement.lastElementChild;
    	}
    	lastElement.style.outline = '2px solid red';
    }

at the end of [`ib.observeMutation`](https://github.com/infinity-next/infinity-next/blob/ccbc102932535f7f9dec1f998ca4a3e469faa98b/public/static/js/app/main.js#L575) to highlight the points to which the document has been loaded each time the callback is invoked.  As expected, when this point is in the middle of a post, quotelinks to the post only load the post up to that point.

![partially-loaded](https://cloud.githubusercontent.com/assets/5894749/11777567/1868c48c-a204-11e5-912c-50ba35933774.png)

Tested in Firefox 42 but it should affect all browsers that implement `MutationObserver`.

**Comment by jaw-sh** [comment]
I've never experienced anything similar to that. This sounds like a Gecko issue. Can you try reproducing this in other browsers?

**Comment by ccd0** [comment]
Also happening in Debian's build of Chromium 46.0.2490.71.

![partially-loaded-chromium](https://cloud.githubusercontent.com/assets/5894749/11778057/eaffde92-a206-11e5-948a-08be4b1145ad.png)

**Comment by jaw-sh** [comment]
Your script is frequently returning false positives and does not support your claim. You're not checking to see if the partially loaded element is actually a part of the widget being bound. A lot of these occurrences I am seeing are way down the DOM. 

```
var lastElement = document.getElementById('page-container');
if (document.readyState === 'loading' && lastElement) {
	while (lastElement.lastElementChild) {
		lastElement = lastElement.lastElementChild;
	}
	
	if ($(lastElement).parents().is(node).length) {
		lastElement.style.outline = '2px solid red';
	}
}
```

**Comment by ccd0** [comment]
`node` is not a widget at that point unless the last node added happened to be a widget.  You want something like

	var widgets = [];
	for (var x = 0; x < records.length; ++x) {
		var nodes = records[x].addedNodes;
		for(var y = 0; y < nodes.length; ++y) {
			var node = nodes[y];
			if (node.attributes && node.attributes['data-widget']) {
				ib.bindElement(node);
				widgets.push(node);
			}
		}
	}
	var lastElement = document.getElementById('page-container');
	if (document.readyState === 'loading' && lastElement) {
		while (lastElement.lastElementChild) {
			lastElement = lastElement.lastElementChild;
		}
		var parentWidget = $(lastElement).parents().filter('[data-widget]')[0];
		if (widgets.indexOf(parentWidget) >= 0) {
			lastElement.style.outline = '2px solid red';
		}
	}

**Comment by jaw-sh** [comment]
This is not how MutationObserver works and your proofs are not indicative that the ECMA specs are improperly implemented on Gecko or Webkit. You are seriously misdiagnosing a different issue. The problem is that the browser caches backlinked posts as HTML. If the post doesn't exist when the cache occurs, it caches incorrectly. This has nothing to do with the MutationObserver and you are pressing the wrong issue and making me write this out needlessly.

**Comment by ccd0** [comment]
It's a problem for any widget that assumes its contents will be available when its `bind` method is called.  The post widget is like that; its `bind` method caches its HTML.  I don't know if any of the others are like that.  If they aren't, you should be okay.

**Comment by jaw-sh** [comment]
mate i'm sorry you're just fucking wrong. http://jsfiddle.net/tp6s0sja/

**Comment by ccd0** [comment]
`MutationObserver`s aren't called immediately on every single change.  They receive batches of changes.
http://jsfiddle.net/y8xgg07w/1/

**Comment by jaw-sh** [comment]
@ccd0 what is your suggestion?
