### ISSUE TITLE
Modify Text parsing

### ISSUE THREAD

**Issue by lluixhi** [infinity-next/infinity-next#204]
infinity-next/eightdown#1
#203 

Changes:
```
Remove >!
>!spoiler!<  changed to ==spoiler==
Added __underline__, removed __bold__
```

It seems that full line spoilering is kind of broken right now because it is implemented on top of block quotes, and I'm not sure whether we really need it.

I feel like using standard Markdown is good, except that removing the ability to underline text is not really an improvement on Infinity's current text rendering.

I realize that parting from standard markdown makes for a bit more maintenance, but I feel like the user base's complaints are valid.

**Comment by jaw-sh** [comment]
@lluixhi Your spoiler implementation doesn't appear to work. Can you review?

**Comment by lluixhi** [comment]
Yeah, I'm looking into it, but I'm kind of stumped.
The closure for spoilers that we're adding into Parsedown as inlineSpoiler() should be called during line(), but it's not, even though we're enabling it in ContextFormatter.

The regex and conditional works, so the only thing I can think of is that maybe ParsedownExtensibility is broken?
We aren't extending Parsedown in the way the creator suggests:
https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions

But I don't really think that should make a difference..

**Comment by interjection** [comment]
```php
	/**
	 * Extends the inline parser dictionary.
	 *
	 * @param  
	 * @return 
	 */
	public function addInlineType($Marker, $Type)
	{
		if (!isset($this->InlineTypes[$Marker]))
		{
			$this->InlineTypes[$Marker] = [];
		}
		
		$InlineTypes = &$this->InlineTypes[$Marker];
		array_unshift($InlineTypes, $Type);

+		if (!strpbrk($this->inlineMarkerList, $Marker))
+		{
+			$this->inlineMarkerList .= $Marker;
+		}
		
		return $this;
	}
```

There should also be no reason to modify parsedown itself for `__` to be formatted as an ins element.

**Comment by lluixhi** [comment]
@interjection 
Do you think overriding the inlineEmphasis method is a better idea?

**Comment by lluixhi** [comment]
infinity-next/eightdown#2
#211 

This change still needs testing, but it should fix spoilers, and it keeps Parsedown intact.
