### ISSUE TITLE
Nothing happens when trying to post

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#209]
Hey,

I've switched to PgSQL, and installation went smoothly
(I would recommend to change the default database from mysql to pgsql in .env.example since mySQL part is not working).

However, posting on my board does not work. I have filled everything, but nothing happens when I click "Create new thread".

I am running Debian 8.2 Jessie, php5, nginx 1.8.0.
You can reach my website here: http://8pallo.fi/b/

Sorry if you are already aware of this, and possibly commiting.
Can't just wait to get this to work, don't want to disturb though.

**Comment by jaw-sh** [comment]
What is your cache driver?

**Comment by weja** [comment]
I haven't configured any. Is this required?
Don't know what is used by default..

**Comment by jaw-sh** [comment]
Your debug bar JavaScript is throwing an error when I try to post, and then even when I do post without using JavaScript the thumbnails don't work because Nginx is misconfigured.

I have no idea why your debug bar is throwing problems.

**Comment by weja** [comment]
Works now. Damn Cloudflare.. Their minify settings broke it.
Sorry for false flag, love your product :+1:

**Comment by jaw-sh** [comment]
Glad it works.
