### ISSUE TITLE
Composer update throws error

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#210]
Hey, wondering why the javascript is still not working, but
now I run composer update and get this error:

[RuntimeException]
  Error Output: [2015-12-16 00:37:19] local.ERROR: exception 'ErrorException'
   with message 'php_strip_whitespace(/var/infinity/infinity-next): failed to
   open stream: No such file or directory' in /var/infinity/infinity-next/ven
  dor/classpreloader/classpreloader/src/ClassPreloader.php:124
  Stack trace:
  #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->h
  andleError(2, 'php_strip_white...', '/var/infinity/i...', 124, Array)
  #1 /var/infinity/infinity-next/vendor/classpreloader/classpreloader/src/Cla
  ssPreloader.php(124): php_strip_whitespace('/var/infinity/i...')
  #2 /var/infinity/infinity-next/vendor/laravel/framework/src/Illuminate/Foun
  dation/Console/OptimizeCommand.php(91): ClassPreloader\ClassPreloader->getC
  ode('/var/infinity/i...', false)
  #3 /var/infinity/infinity-next/vendor/laravel/framework/src/Illuminate/Foun
  dation/Console/OptimizeCommand.php(72): Illuminate\Foundation\Console\Optim
  izeCommand->compileClasses()
  #4 [internal function]: Illuminate\Foundation\Console\OptimizeCommand->fire
  ()
  #5 /var/infinity/infinity-next/vendor/laravel/framework/src/Illuminate/Cont
  ainer/Container.php(503): call_user_func_array(Array, Array)
  #6 /var/infinity/infinity-next/vendor/laravel/framework/src/Illuminate/Cons
  ole/Command.php(150): Illuminate\Container\Container->call(Array)
  #7 /var/infinity/infinity-next/vendor/symfony/console/Command/Command.php(2
  56): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\I
  nput\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #8 /var/infinity/infinity-next/vendor/laravel/framework/src/Illuminate/Cons
  ole/Command.php(136): Symfony\Component\Console\Command\Command->run(Object
  (Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Conso
  le\Output\ConsoleOutput))
  #9 /var/infinity/infinity-next/vendor/symfony/console/Application.php(838):
   Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\Arg
  vInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #10 /var/infinity/infinity-next/vendor/symfony/console/Application.php(189)
  : Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Fou
  ndation\Console\OptimizeCommand), Object(Symfony\Component\Console\Input\Ar
  gvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #11 /var/infinity/infinity-next/vendor/symfony/console/Application.php(120)
  : Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Con
  sole\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutpu
  t))
  #12 /var/infinity/infinity-next/vendor/laravel/framework/src/Illuminate/Fou
  ndation/Console/Kernel.php(107): Symfony\Component\Console\Application->run
  (Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Componen
  t\Console\Output\ConsoleOutput))
  #13 /var/infinity/infinity-next/artisan(36): Illuminate\Foundation\Console\
  Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Sy
  mfony\Component\Console\Output\ConsoleOutput))
  #14 {main}

Don't know if it's any related to js errors though.

**Comment by jaw-sh** [comment]
This is not an issue with Next. This is a known problem with Composer that they refuse to fix because they're faggots.

**Comment by DeeJaVu** [comment]
so what to do about ?
