### ISSUE TITLE
Attachment Wrapper Min Height Causes Issues with videos and responsive css

### ISSUE THREAD

**Issue by Graham--M** [infinity-next/infinity-next#223]
If an attachment has a thumbnail, its wrapper is given a `min-height` and `min-width` corresponding to the dimensions of the thumbnail, [in this method](https://github.com/infinity-next/infinity-next/blob/5ce63217bb9e46f0045c1c8ce7fa976861a91e68/app/FileStorage.php#L642).

The problem is that in small screens, the css scales the thumbnails down with a `max-height` as shown [here](https://github.com/infinity-next/infinity-next/blob/5ce63217bb9e46f0045c1c8ce7fa976861a91e68/public/static/css/app/responsive.css#L40) but not the wrapper. This means that a large gap appears between the thumbnail and attachment details.

![capture2](https://cloud.githubusercontent.com/assets/8626636/12091001/86683254-b2eb-11e5-98c8-44419986045f.PNG)

This also happens for audio files with a thumbnail and means that the record background image is much bigger than the thumbnail cover.

![capture1](https://cloud.githubusercontent.com/assets/8626636/12091000/8662c13e-b2eb-11e5-90f7-47c5201ac3e1.PNG)

*Note that clicking on a thumbnail for an image or audio file removes the `min-height` property from the wrapper*

Another issue this causes is that when opening video files like webms the thumbnail is hidden but the attachment wrapper still has its `min-height` set, again leaving a large gap between the video player and the attachment details.

![capture3](https://cloud.githubusercontent.com/assets/8626636/12091002/866f1f4c-b2eb-11e5-8740-a25876f31c9d.PNG)

Both of these issues disappear when the `min-height` rule is removed from the wrapper in the web inspector.

What reason is the `min-height` rule added to the wrappers for thumbnails?

**Comment by jaw-sh** [comment]
To conserve space on mobile devices, and to keep thumbnails looking good 
with a 2x DPI. I'll see if I can deal with the thumbnail scaling without 
removing the feature because I do like it.

**Comment by Graham--M** [comment]
I'm not sure what you mean by that. I tried using an ipad and the emulation mode in chrome but removing the `min-height` doesn't seem to do anything to the thumbnail size on small or regular high dpi screens.

Would the `min-resolution` feature of the `@media` query be a better candidate for dealing with high dpi issues?

**Comment by jaw-sh** [comment]
@Graham--M I believe this is resolved. Can you confirm?

**Comment by Graham--M** [comment]
Yes. The fixed sizing on the thumbnails stops the scaling issue, and #228 gets rid of the gap under expanded video attachments.
