### ISSUE TITLE
Contributors Agreement

### ISSUE THREAD

**Issue by jaw-sh** [infinity-next/infinity-next#238]
Due to recent claims made on the project (see: https://infinitydev.org/ or https://archive.is/w1k3Z), I am clarifying the contributor's agreement.
This is to protect the project and to ensure it will be continue to be maintained, protected, open, and free forever.

By submitting your agreement, you are ensuring your contributions into the project also remain free and responsibly used.
Infinity Next's AGPL3 license protects all of our contributions from ending up being closed source.
As long as this license is kept, people using our work will be required to keep their project free in the same way.

Please read and agree to the following license, and submit forward your agreement to josh@jaw.sh, or post them here with the same account the contributions were made with.

https://github.com/infinity-next/infinity-next/blob/master/contributors

In this email, I require from you the following information.

1. Email
2. Name
3. Country
4. Phone or Skype
5. A copy of the license in your email and explicit instruction that you agree to it.
6. Corporate Contributor Information. If you work for a company where your code might end up belonging to that entity, please describe your situation.

I also warmly welcome any comments or questions, either via email or here.

The following contributors must agree to this license as I have described, or they must remove their code from the repository.

- [ ] @ccd0
- [ ] @tmrwbo
- [ ] @Graham--M
- [ ] @ctrlcctrlv
- [ ] @milezteg
- [ ] @nuew
- [ ] @zefredz
- [ ] @odilitime
- [ ] @ZiRo-
- [ ] @interjection
- [ ] @lluixhi

Please respond promptly. If I do not receive an agreement or removal request in a week's time, I may be forced to remove your contributions.
I hope you can appreciate the time sensitivity with this matter. I would love to give you more time to review, however circumstances as they are must force me to act quickly.

**Comment by ctrlcctrlv** [comment]
People implicitly agree to a license when they submit code to a project licensed that way. You only have to do this when changing licenses.

You're confusing "copyright holder" and "license". If a lawyer gave you this advice, lol.

Also you can put me down for "you're an idiot with no understanding of FOSS licenses wasting people's time by making them re-agree to something they agreed to when submitting code".

**Comment by nuew** [comment]
Agree with Frederick completely.

**Comment by Graham--M** [comment]
I also assumed anything I was submitting was under the AGPL3 used.

But I'll explicitly state that past and any future contributions from me to this project are made under [this license](https://github.com/infinity-next/infinity-next/blob/7b74c061dafabb65fcea25b589966acc86fbdd8f/contributors).

I feel the other details are in excess of what is required to agree to the license.

**Comment by ctrlcctrlv** [comment]
Agreed with @Graham--M. This is a meme website, not Google; no one should have to release their dox to you to agree to something they already agreed to, this is bizarre. I think you should cancel this.

**Comment by zefredz** [comment]
I agree with the previous comments.

**Comment by jaw-sh** [comment]
I'll talk to a few people about what should be done. I may end up removing this contractual agreement for implicit agreement, my intention isn't to inconvenience anyone. I just want to protect the project and people's work. All of my efforts are going towards keeping the project open source and any projects building off of it as well.

**Comment by Taywee** [comment]
Do you know how the AGPL works?  You can't contribute non-AGPL code to an AGPL project.  That's one of the most basic tenets of GPL and AGPL in the first place.  The agreement is superfluous.

**Comment by tmrwbo** [comment]
Already agreed when I submitted commits same as everyone else here said. Not doxing myself for this project. And I will probably not be committing anything more if you are going to fuck 8chan over in the end. You can keep the minor commits I made, but both you retards need to quit acting like babies and suck it up and get along. This is fucking retarded. Do what's best for 8chan and quit acting like little girls.

**Comment by ccd0** [comment]
I think the ability to improve the board anonymously is important, and should be kept going forward, even if it means diverging from Josh's fork.

Also, if you actually read
https://github.com/infinity-next/infinity-next/blob/7b74c061dafabb65fcea25b589966acc86fbdd8f/contributors
it relicenses contributions under the terms of the Apache License.

**Comment by jaw-sh** [comment]
@Taywee Which is why most people don't have a CLA on their open source projects. Contributing code implies everything listed in this agreement, but larger projects tend to have CLA for liability reasons. I'm not as worried as I was a few hours ago, so I'll probably end up dropping this requirement. I really do just want to protect the AGPL, open-source nature of Next and ensure any instances of it do not feature malicious code that would violate the user's privacy.

@tmrwbo I understand. This is frustrating for me as well. I really wanted to help 8chan but there's nothing I can do for it now. It's out of my control. The only thing I can do is continue developing it to meet other expectations.

@ccd0 Fair points.

I won't delay this. I apologize for wasting your time with this. I will probably go ahead and remove Frederick's code, as not only does it post a risk, but he probably copied the logic directly from Tinyboard and I do not believe he is authorized to do so. I don't know the specifics on this but it's not worth the risky. I will likely feature a unique implementation of tripcodes in Next if and when I am able to sit down comfortably and continue my work.

**Comment by mrseth** [comment]
>not feature malicious code that would violate the user's privacy.
Says the guy that doesn't give a fuck if he leaks user's ips.
Could you stop being a bullshitter faggot for a minute or two?
