### ISSUE TITLE
gibe Infinity-Next pl0x

### ISSUE THREAD

**Issue by tuy360** [infinity-next/infinity-next#240]
gibe Infinity-Next pl0x

**Comment by jaw-sh** [comment]
You have to write a big rant calling me fat first.

**Comment by tuy360** [comment]
Josh is so freaking fat. That fatso Josh is the fattest. He redefines the meaning of "fat". Why can't Josh look past all his fat and see that he's fat? It must be because he's simply too fat. You couldn't pay me to be as fat as Josh Moon. There is fat and then there's Josh. He and his fat are inseparable. Fat Josh is what people should call him. Standing next to Josh Moon, Fat Albert would look anorexic. What does he drive? A fatmobile? As if his fat would fit in a car. He is absolutely obese. You could take shelter under Josh's fat. He's so fat I can almost see him in the distance as I type this. Joshua "Fatty Fatso McFatterson" Moon was unable to stop being so fat that he couldn't complete Infinity-Next. More like "Infatiny-Next" or "Infinity-Fat". Josh's abdominal was so stretched that his stomach ulcer practically burst open and he was unable to stop being so fat. TL;DR Josh is fat.

**Comment by SEAPUNK** [comment]
someone give this man a medal

**Comment by jaw-sh** [comment]
Well, I guess I have no choice now. I'll give an update in about a week.
