### ISSUE TITLE
Board listing missing

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#242]
On "Admin panel" boards page it does not display boards, the part of the page where it should be is blank. I can directly add boards via adminer to database and it works. DEBUG does not show any exceptions.

I cannot really troubleshoot better, but you can try the same in my instance,
https://8pallo.fi username Admin password Password123

**Comment by milezteg** [comment]
You need to check out the `roles` or `user_roles` table and make sure the permissions are correct.  I remember I needed to do this once but not exactly sure what needed to be changed tbh.  You also might need to save global settings once to establish those are being added.

**Comment by weja** [comment]
in roles table there are two user.role.board_owner, other with weight 60 and other 65. Don't know if this is intended, also the other user.role.board_owner is last on the list (id 9). I also add group 8 (absolute) to my user, but I don't see problem fixed.. Or it's the caching preventing me from seeing changes yet.

**Comment by jaw-sh** [comment]
Fixed with 6a7ef99f0a186c2ab710b37c68ca3301f26f4c75
