### ISSUE TITLE
more like

### ISSUE THREAD

**Issue by chick8ed** [infinity-next/infinity-next#243]
INFINITY NEVER
FUCK YOU JOSH

**Comment by jaw-sh** [comment]
Frederick is still allowed to use it, but Jim refuses to let him because he wants a licensing change. He can literally download it right this second, set it up, and have people use it. Jim doesn't want that because his changes would have to be open source.

**Comment by ctrlcctrlv** [comment]
> He can literally download it right this second, set it up, and have people use it.

Only if it actually worked under load, you mean. You're mischaracterizing the problem. The license change were only for the third party RQI developers to work on it.

**Comment by ctrlcctrlv** [comment]
Also my name is Fredrick

**Comment by jaw-sh** [comment]
>Only if it actually worked under load, you mean. You're mischaracterizing the problem. The license change were only for the third party RQI developers to work on it.
RQI is allowed to work on it right now, but Jim wants their work to be closed for 8chan. Stop trying to lie about licensing.

**Comment by ctrlcctrlv** [comment]
No one is lying. We still could use it if it worked under our load, no matter who makes it work; whether you can make it work is a great mystery, thus the offer for others to do it for you.

Even if you make it work, the production 8chan probably won't be using it -- your response to matters of user security such as IP leaks and the decision of the user referendum sealed that fate. But there is no way we could just download the present source code and "make it work", you tried enough yourself, di ba?

**Comment by jaw-sh** [comment]
You're shifting blame and intentionally instigating me. You can sit up 
on your motorized thrown and do your chicken dance laugh all you want. 
_YOU_ picked this license and _YOU_ decided to blackmail me and publish 
a hit article before I even had a chance to think of a number. You 
successfully burned this bridge without a moment's thought and now that 
Jim is mad at you, you're taking it out on me.

I was going to let this go but it's obvious you're going to keep coming 
after me so now I'm telling my side.

Get out of my project, mate.

**Comment by ctrlcctrlv** [comment]
>motorized thrown
kek

Jim isn't mad at either of us. You have a very strange habit of ascribing emotions to people which they are not feeling.

>Get out of my project, mate.
Gladly.

**Comment by gothmob** [comment]
Looks like you need a CoC here.

**Comment by milezteg** [comment]
related: https://www.youtube.com/watch?v=bW7Op86ox9g

**Comment by gothmob** [comment]
@milezteg I would upvote that were I able.

**Comment by SEAPUNK** [comment]
@gothmob use emojis instead

:100: :ok_hand: :laughing: :fire: :ok_hand: :fire: :laughing: :ok_hand: :100:

**Comment by Kagami** [comment]
>Looks like you need a CoC here

Here you are: :eggplant:

**Comment by jaw-sh** [comment]
Official CoC is indeed :eggplant:. Thanks for complying.
