### ISSUE TITLE
Blank page with newest update

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#247]
I made fresh install, get blank page and this:

[error] 5942#0: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/html/infinity-next/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/infinity-next/bootstrap/autoload.php on line 17
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/html/infinity-next/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/infinity-next/bootstrap/autoload.php on line 17" while reading response header from upstream, client: 141.101.80.205, server: ***.fi, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "***.fi"

**Comment by jaw-sh** [comment]
/vendor/ files are not included in the Git repository.

Run:
/var/www/html/infinity-next/composer.phar update

**Comment by weja** [comment]
Oh shit I forgot composer update.. Never again try to make fresh install from memory..
Sorry to bother. Maybe this would need install.php for people like me :s

**Comment by jaw-sh** [comment]
np
