### ISSUE TITLE
oy vey

### ISSUE THREAD

**Issue by ShlomoShekelberg** [infinity-next/infinity-next#251]
This project is very antisemitic. The developer is a scam artist that robbed me of shekels and failed to deliver. oy vey it's like anudda shoah.

**Comment by jaw-sh** [comment]
Code's right there m8.

**Comment by ShlomoShekelberg** [comment]
You and I both know that code doesn't work, goy. It will not scale. The nation of Israel needs an image board that scales. It must be able to handle the load of at least 6 million Jews.

**Comment by jaw-sh** [comment]
Works for me. Must be you.

**Comment by milezzz** [comment]
@ShlomoShekelberg BOOOOOOORRING.
