### ISSUE TITLE
Editing navigation?

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#256]
This might be a little stupid question, but how do I edit navigation?

I would like to remove certain links, and add few own. I find it a little difficult to make clear difference between "new thread" and "new board" (for new chan user at least), so I would like to redo navigation bar.

I don't mind editing file manually and adding/removing lines, but I cannot figure out how "$navItem" works, or how they are listed (or where).

Thanks in advance.

**Comment by jaw-sh** [comment]
Are you referring to primary navigation or in-board navigation?

Try this file:
https://github.com/infinity-next/infinity-next/blob/master/app/Services/SettingManager.php

It was put here because I originally intended for links to be managed by 
the setting manager.

**Comment by weja** [comment]
Thank you, exactly what I needed.
I prefer to have this functionality via cp though, this is something what everyone probably wants to edit adding their own links etc.

**Comment by jaw-sh** [comment]
I agree. As I said, the reason it's located in such an odd place is 
because the intention was to eventually offload that responsibility to 
the site configuration.
