### ISSUE TITLE
No images on "recent posts" on front page

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#257]
Any idea why recent images no longer display on front page?
I have fixed my nginx config, images work elsewhere

My website: https://8pallo.fi

**Comment by jaw-sh** [comment]
The front page, by default, does not display images from NSFW boards.

There's no setting for this, you have to edit this template:

https://github.com/infinity-next/infinity-next/blob/master/resources/views/content/index/sections/recent_images.blade.php

Set the "false" to "true" in ::getRecentImages.

**Comment by weja** [comment]
Okay, it's a little disturbing that posts from NSFW boards get to front page, but images not.
But I understand the reasoning behind banning images from NSFW boards, everyone does not want to see this material.

**Comment by jaw-sh** [comment]
@weja You can make the inverse change to recent_posts. Just turn `true` to `false` in the getRecentPosts method.
