### ISSUE TITLE
Error creating board (anonymous user)

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#259]
Creating board is broken, yesterday it created user, said  "Oops, something went wrong" and didn't create board, today it didnt create user nor board. I had to manually add users to users table because there is no registration option for moderators etc, maybe this is causing it..

Error in nginx log:
[error] 1279#0: *818 FastCGI sent in stderr: "PHP message: [2016-02-18 10:50:30] local.ERROR: exception 'PDOException' with message 'SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (user_id)=(5) already exists.' in /path/to/inf//vendor/laravel/framework/src/Illuminate/Database/Connection.php:321
Stack trace:
#0 /path/to/inf/vendor/laravel/framework/src/Illuminate/Database/Connection.php(321): PDOStatement->execute(Array)
#1 /path/to/inf/vendor/laravel/framework/src/Illuminate/Database/Connection.php(644): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'insert into "us...', Array)
#2 /path/to/inf/vendor/laravel/framework/src/Illuminate/Database/Connection.php(611): Illuminate\Database\Connection->runQueryCallback('insert into "us...', Array, Object(Closure))
#3 /path/to/inf/vendor/laravel/framework/src/Illuminate/Database/Connection.php(324): Illum" while reading response header from upstream, client: ****, server: 8pallo.fi, request: "POST /cp/boards/create HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "8pallo.fi", referrer: "https://8pallo.fi/cp/boards/create"

**Comment by jaw-sh** [comment]
You're correct. Your primary key value is out of sync with your table.

1 admin
2 user
3 user2

pkey=1

so it goes to insert a new user named "user3" and assumes its ID will be 
2 because the last pkey was 1.

**Comment by weja** [comment]
I was a little unsure how to fix it (ids seemed to be correct for me..), so I just retried creating board like 5 times, and every time it tried inserting 1 higher id value.. Now it works again.
