### ISSUE TITLE
Reading reports in cp does not work

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#260]
Tried testing the report feature, reporting globally seems to work, but when I try to view it in cp clicking "Reports" it says "Oops, something went wrong".

nginx error log:
[error] 1277#0: *705 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function toText() on string in /path/to/inf/storage/framework/views/8ebb8d69130aad2cd6fa0de53765c36f on line 37
PHP message: [2016-02-18 10:01:26] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function toText() on string' in /path/to/inf//storage/framework/views/8ebb8d69130aad2cd6fa0de53765c36f:37
Stack trace:
#0 {main}" while reading response header from upstream, client: ***, server: 8pallo.fi, request: "GET /cp/boards/reports HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "8pallo.fi", referrer: "https://8pallo.fi/cp/boards/appeals"

**Comment by weja** [comment]
Any idea what could be causing this..? Seems to work on 16chan..

**Comment by weja** [comment]
Coulds this have anything to do with laravel crontab..? I set it up earlier today (hours ago), and suddenly reports started working.. Like 5 minutes ago..

**Comment by jaw-sh** [comment]
Why'd you close this? Sounds like it's a live issue.
