### ISSUE TITLE
Reserve nickname?

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#265]
Would it be possible to reserve nickname?

Like, my username is Waltsu, is it possible that others cannot use the same nickname on their posts?
I can choose whether I want to display my username on my replies or not. So I can post anonymously if I want, too. Reserving a nickname could be "paid" feature. Easy way to fund an imageboard. On the other hand to make it work, the entire posting with nickname should be disabled, unless you reserve a nickname.

I know this fights against the idea of anonymity, but normalfags would like this feature.
I plan on building something little different, than "regular imageboard" anyways.

**Comment by milezzz** [comment]
Dude, just no.  You need to do some reading:  https://en.wikipedia.org/wiki/Imageboard#Tripcodes

Also do you really have to clutter up the issues area with a thousand requests?

**Comment by jaw-sh** [comment]
I think he's referring to account usernames and not the name field.

**Comment by weja** [comment]
I thought the idea was to make new issue for each and not all issues in same post.. After all they are issues, and stuff is still broken. But I'll stop, feel free to remove them all. Sorry.
