### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'body_has_content' in 'where clause'

### ISSUE THREAD

**Issue by ttomasic-ofc** [infinity-next/infinity-next#267]
Hi,

after running "php artisan db:seed", I get an error about a column missing ('body_has_content').

Here is the complete error output:

http://paste.debian.net/418350/

What should I do?

**Comment by jaw-sh** [comment]
Try running `php artisan migrate` first. Your installation must be incomplete.

**Comment by ttomasic-ofc** [comment]
I created a new database, specified it in .env.
Then I re-ran "php artisan migrate" & "php artisan db:seed".

After that I no longer get the error about columns,
but the homepage does not load properly. (see screenshot)

![inf](https://cloud.githubusercontent.com/assets/15815107/13987051/0a172166-f106-11e5-8932-3bbafe8ca5cc.png)

**Comment by jaw-sh** [comment]
That's a weird issue I sometimes get. If you change `base_url` in `config/minify.config.php` to `env('APP_URL', 'static')`, it should work, but it'll stop working if you go into production -- and vice versa. I think it's an issue specifically with the minification mod.

**Comment by ttomasic-ofc** [comment]
Thanx, now the homepage loads properly.

However, when I try to create a board, I get:

The requested URL /cp/boards/create was not found on this server.

I presume 'cp' refers to some kind of control panel.
Should that be a table in the DB?

I have the following tables:

ban_appeals                  |
| ban_reasons                  |
| bans                         |
| board_adventures             |
| board_assets                 |
| board_settings               |
| board_tag_assignments        |
| board_tags                   |
| boards                       |
| cache                        |
| captcha                      |
| file_attachments             |
| files                        |
| logs                         |
| migrations                   |
| option_group_assignments     |
| option_groups                |
| options                      |
| pages                        |
| password_resets              |
| payments                     |
| permission_group_assignments |
| permission_groups            |
| permissions                  |
| post_checksums               |
| post_cites                   |
| posts                        |
| reports                      |
| role_cache                   |
| role_permissions             |
| roles                        |
| sessions                     |
| site_settings                |
| stats                        |
| stats_uniques                |
| user_roles                   |
| users           |

**Comment by jaw-sh** [comment]
Your webserver isn't configured properly.

**Comment by ttomasic-ofc** [comment]
I configured apache2 according to the wiki:

https://github.com/infinity-next/infinity-next/wiki/Installation

DocumentRoot points to public subdir. DirectoryIndex points to index.php.

XSendFile is optional, so apart from these I don't really see what could be misconfigured.

Any ideas?

**Comment by jaw-sh** [comment]
No, but if you're getting a non-Laravel error for 404 that's what the problem is.

**Comment by bakugo** [comment]
I may be wrong, but I'm pretty sure the apache config in the wiki is wrong. There's nothing in it to rewrite requests to index.php, so any requests that aren't made directly to index.php won't work.

Try adding something like this inside the vhost:
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
```

**Comment by ttomasic-ofc** [comment]
On apache2.4 that mod_rewrite conf results in goofy redirect loops.

I added this line, per apache2 docs:

`        FallbackResource "index.php"`

Worked like a charm.

Thanx for the help, my dewds.
