### ISSUE TITLE
Images not displayed - "The Response content must be a string or object implementing __toString(), "object" given."

### ISSUE THREAD

**Issue by syst0m** [infinity-next/infinity-next#270]
I see a select passed to MySQL that fetches the file by hash,
but no image gets displayed on the board.

Could you, please, help me with this error?

Full trace:
http://paste.debian.net/418601/

**Comment by DeeJaVu** [comment]
same here

**Comment by DeeJaVu** [comment]
damn someone has a fix ?

**Comment by DeeJaVu** [comment]
finnaly found the fix

this is the steps i did for my ubuntu 15.10 server

1. sudo apt-get install libapache2-mod-xsendfile
2. sudo a2enmod xsendfile
3. sudo service apache2 restart

then edit your virtual host file for example

```
<VirtualHost *:80>
    DocumentRoot "/var/www/infinity-next/public"

    <Directory "/var/www/infinity-next/public">
        AllowOverride all
       Options +Includes -Indexes +ExecCGI
    </Directory>
   
    ## this is important !
    <IfModule mod_xsendfile.c>
        XSendFile on
        XSendFilePath "/var/www/infinity-next/"
    </IfModule>
</VirtualHost>
```

then `sudo service apache2 restart`

now the images should be displayed

**Comment by syst0m** [comment]
thank you a gadzillion, @DeeJaVu.
that did the trick.
