### ISSUE TITLE
Clearnet boards are broken

### ISSUE THREAD

**Issue by gubbug** [infinity-next/infinity-next#273]
going to any board through clearnet doesnt work along with opening a thread on clearnet.
overboard and homepage are fine

**Comment by jaw-sh** [comment]
Please define "doesn't work" with screenshots and error messages.
Is this 16chan related or your own intallation?

**Comment by gubbug** [comment]
on 16chan.nl when you go to any board you get this

![](https://i.imgur.com/QD6E1KY.png)

**Comment by jaw-sh** [comment]
That's.. odd. That looks like CSS is failing to load in -- along with half the page.

Few things.
- What browser?
- Does your f12 console say anything?
- Can you view the page source and send me the HTML?

**Comment by gubbug** [comment]
chromium
f12 does show stuff
source https://ghostbin.com/paste/bs9tc

**Comment by milezzz** [comment]
Looks like it is the captcha breaking...

https://ghostbin.com/paste/nbnmd

**Comment by jaw-sh** [comment]
@milezzz is right. Made a stupid error by failing to `use Session`. One sec.

**Comment by jaw-sh** [comment]
Appears up now. Please confirm. I feel really stupid for that mistake :$

**Comment by gubbug** [comment]
seems fixed. thanks
