### ISSUE TITLE
laravel wants missing rev-manifest.json

### ISSUE THREAD

**Issue by ZiRo-** [infinity-next/infinity-next#277]
When trying to set up a new instance I get the following error

```
vendor/laravel/framework/src/Illuminate/Foundation/helpers.php line 280:

file_get_contents(.../public/build/rev-manifest.json): failed to open stream: No such file or directory
```
Looking through the commit logs, you recently removed this file, with no indication on how to generate it.

**Comment by jaw-sh** [comment]
Use `npm gulp`.

**Comment by ZiRo-** [comment]
Add that to the README then
