### ISSUE TITLE
Implement tripcodes

### ISSUE THREAD

**Issue by ctrlcctrlv** [infinity-next/infinity-next#28]
The current tripcode system, first written by 2ch in the 90's, is implemented like this:

https://github.com/ctrlcctrlv/infinity/blob/master/inc/functions.php#L2751-2785

In short, it works by using a publicly known salt and the thoroughly busted PHP `crypt()` function which implements the so called "Data Encryption Standard", [first written by IBM in the 1970's](https://en.wikipedia.org/wiki/Data_Encryption_Standard).

[DES is thoroughly broken.](https://www.sans.org/reading-room/whitepapers/vpns/day-des-died-722)

A program exists that can [crack entire tripcodes in 48 hours or less on modern GPUs](http://harry.lu/mty/).

Even less advanced users who only have CPU power at their disposal can [crack the beginning 4-5 characters of a trip in hours](http://desktopthread.com/Tripcode_Explorer/), which is enough to fool most people as they don't have the whole trip memorized.

The nice thing about the 2ch system was that tripcodes on 2ch work everywhere: 2chan.net, 4chan, 8ch, 7chan...unfortunately, they're very broken already and it won't be long until completely inadept users can track any trip on an hour.

I will implement [Overchan-style message singing in infinity-next](http://anonet2.biz/Overchan.html#Signatures) using ED25519. Since this is a signing algorithm and not symmetric encryption like trips, it is even possible (but of course not default) to sign your message offline and not even trust the site with your key. This is suitable to even be used for admin messages.

In order to be easy for inexperienced users, [a pure PHP fallback will be used by default](https://github.com/trianglman/sqrl/blob/master/
src/Trianglman/Sqrl/Ed25519/Crypto.php). [Users will be recommended to compile the PHP libsodium for best security though](https://github.com/jedisct1/libsodium-php)!

**Comment by mofosyne** [comment]
I love the idea of public/private key signing system for this.

In reference to "feature request: Alternative to tripcode #514", can you also provide an alternative representation of the "public key" fingerprint, in the form of a memorable sentence? 

E.g. "ctrlcctrlv - The wandering maverick of yore" generated from some fingerprint like "ctrlcctrlv - A3:B5:6E:4F:E2"

**Comment by lulalala** [comment]
It's interesting to learn that a tripcode system using asymmetric encryption is possible.  I want to learn more.  But that overchan link is broken. Is there other materials to read about?
