### ISSUE TITLE
Call to undefined method Illuminate\Database\Schema\Blueprint::inet()

### ISSUE THREAD

**Issue by lowyse** [infinity-next/infinity-next#290]
I'm getting this error when I run the command `php artisan migrate`:

```
# php artisan migrate
Migration table created successfully.
PHP Fatal error:  Call to undefined method Illuminate\Database\Schema\Blueprint::inet() in /var/www/nginx/html/database/migrations/2016_01_18_213303_captcha_index.php on line 23

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Illuminate\Database\Schema\Blueprint::inet()

```

**Comment by lowyse** [comment]
I fixed it modifying the line 23 from `infinity-next/database/migrations/2016_01_18_213303_captcha_index.php`

Before:
`$table->inet('client_ip')->after('hash')->nullable();`

After:
`$table->string('client_ip')->after('hash')->nullable();`

**Comment by jaw-sh** [comment]
you absolutely did not. all you did was break everything that relied on
that code.

**Comment by lowyse** [comment]
If you say so.. It's working for me

**Comment by SEAPUNK** [comment]
Are you using MySQL? That might be why the code didn't work for you -- I'm pretty sure the code is designed to run on Postgres.

**Comment by lowyse** [comment]
Yes. I just tried Postgres and I got the same error.
