### ISSUE TITLE
Two Errors encountered during install on a fresh 14.04 server

### ISSUE THREAD

**Issue by Connor22** [infinity-next/infinity-next#294]
**SETUP** 
Starting on a fresh install of Ubuntu 14.04 with MyPHPAdmin, MySQL, Apache, and PHP installed. Server is hosted on DigitalOcean, and is the `PHPMyAdmin 14.04` preset VM

In MySQL, a `next` user is created alongside a `next` database, and is given full permissions. The `.env` file looks like [this](http://hastebin.com/raw/yivequwala)

**ERROR #1**
`composer update` runs fine once dependencies are installed, but `php artisan migrate` throws:

```
PHP Fatal error:  Call to undefined method Illuminate\Database\Schema\Blueprint::inet() in /var/www/next/database/migrations/2016_01_18_213303_captcha_index.php on line 23
```

Editing this line lets you bypass this error, but I've seen in a different issue that you say this breaks other things. Maybe this is what causes the next error.

**ERROR #2**
For `php artisan db:seed`, the Admin is set up fine, but it throws this error afterwards.

```
 [InvalidArgumentException]
 Cache store [file] is not defined.
```

`CACHE_DRIVER` is set to `file` in `.env`. I don't believe I'm supposed to change that, but feel free to let me know if I'm wrong.

After this, the server only responds with a 500 error.

**Comment by ev1l0rd** [comment]
To fix error 1, see this commit: https://github.com/interjection/infinity-next/commit/f248c44c947721529ed80d06b02be1599a2d5fbb . Basically, lavarel changed, but the current code is out of date.

**Comment by jaw-sh** [comment]
3 and a half year old issue. See #298
