### ISSUE TITLE
syntax error, unexpected 'throw' (T_THROW)

### ISSUE THREAD

**Issue by eldarkhanov** [infinity-next/infinity-next#295]
FatalErrorException in ContentFormatter.php line 518:
syntax error, unexpected 'throw' (T_THROW)

When adding thread

**Comment by jaw-sh** [comment]
That line should look like this:

```
                    $throw = Dice::throw(
```

What version of PHP are you using? It seems to explicitly reserve `throw` as a variable name.

**Comment by AzAzzAzzz** [comment]
I use version 5.6, the exception is thrown when adding a thread or any other data

**Comment by AzAzzAzzz** [comment]
I checked for different versions of the same error

**Comment by jaw-sh** [comment]
With php >= 7.3 and cccc6f23d7a7103f28f3ec354396004825e5d75a it should no longer throw this.
