### ISSUE TITLE
"php artisan migrate" spews out error 

### ISSUE THREAD

**Issue by sp3rg** [infinity-next/infinity-next#296]
Hey, so I clone the repository, and then do "composer update" and then type "php artisan migrate" and then it gives me this error below.

`PHP Warning:  require(/var/www/inf/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/inf/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/inf/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/inf/bootstrap/autoload.php on line 17`

thanks
- will

**Comment by Some-T** [comment]
sounds like your directories are wrong
