### ISSUE TITLE
'factories' directory missing

### ISSUE THREAD

**Issue by hawkoon** [infinity-next/infinity-next#297]
When running the 'composer update' command, it throws an error regarding the missing folder 'database/factories'.
![error](https://user-images.githubusercontent.com/54553501/67618971-5fa25380-f7f6-11e9-9d58-0d4be4c34a52.png)

**Comment by hawkoon** [comment]
@jaw-sh

**Comment by jaw-sh** [comment]
f31e79ebed9009701ed69ed21c2831e50d68270d
