### ISSUE TITLE
Trying to configure and install to a new website

### ISSUE THREAD

**Issue by sas6323** [infinity-next/infinity-next#298]
I don't know if anyone can possibly help me or maybe lead me in the right direction.  I'm trying to install the PHP script onto by server and I don't really know what to do.  I don't know what files to configure, how to configure, or even how to install it to the server.  I installed a SQL database on the web server but that is all I have done.  Any help would be appreciated.

**Comment by hawkoon** [comment]
infinity-next seems to be pretty broken and isn't maintained. You should try LynxChan or vichan instead.

**Comment by jaw-sh** [comment]
The codebase is currently between framework versions and is being updated. No promises. I do have a working copy up. Clone the repo, `composer install`,, `npm run`, `php artisan migrate`, `php artisan db:seed`, make note of the admin password.
