### ISSUE TITLE
php artisan migrate gives database error

### ISSUE THREAD

**Issue by hawkoon** [infinity-next/infinity-next#299]
EDIT: I got a lot further by using MYSQL instead of MariaDB. I was able to login and generate the default error page, but that's it. I had to change a lot of stuff in the source code and doing anything else gave a lot of errors. I also couldn't reach /test/. Bottom line: still a lot fixing is needed.

**Comment by jaw-sh** [comment]
You'll have to use Postgres as that's all I'm testing for at the moment.

**Comment by hawkoon** [comment]
Just tried installing on a fresh distro install. After ``composer install`` I tried running `npm run dev` but get the following error:

> [root@localhost html]# npm run dev
> 
> @ dev /var/www/html
> npm run development
> 
> > @ development /var/www/html
> > node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
> 
> internal/modules/cjs/loader.js:979
>   throw err;
>   ^
> 
> Error: Cannot find module '/var/www/html/node_modules/cross-env/src/bin/cross-env.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:859:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ development: `node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @ development script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-04-04T18_07_08_317Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ dev: `npm run development`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @ dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-04-04T18_07_08_341Z-debug.log
>

**Comment by hawkoon** [comment]
Next error when running `php artisan migrate`:

>    Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE')
> 
>   at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
>     665|         // If an exception occurs when attempting to run a query, we'll format the error
>     666|         // message to include the bindings with SQL, which will make this exception a
>     667|         // lot more helpful to the developer instead of just the database's errors.
>     668|         catch (Exception $e) {
>   > 669|             throw new QueryException(
>     670|                 $query, $this->prepareBindings($bindings), $e
>     671|             );
>     672|         }
>     673|
> 
>   Exception trace:
> 
>   1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [2002] No such file or directory")
>       /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31
> 
>   2   PDOException::("SQLSTATE[HY000] [2002] No such file or directory")
>       /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

**Comment by jaw-sh** [comment]
Are you using PgSQL?

**Comment by hawkoon** [comment]
> 
> 
> Are you using PgSQL? I am only testing PgSQL at the moment, but I will accept a MySQL PR.

This time indeed I am! Manually created a database called 'forge' and added the info to the .env file. Now getting:

>   Illuminate\Database\QueryException  : could not find driver (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE')

Even though I have php-mysql installed.

**Comment by jaw-sh** [comment]
php-mysql is only for mysql. `apt-get install php7.3-pgsql`

**Comment by hawkoon** [comment]
> 
> 
> php-mysql is only for mysql. `apt-get install php7.3-pgsql`
> 
> Postgres is not like MariaDB. It is an entirely unique application with a different implementation of the SQL specification.

That makes sense lol. Thanks First time using Postgres. I'll fiddle with the database some more.

**Comment by hawkoon** [comment]
Managed to successfully run `php artisan migrate` and `php artisan db:seed`. Having trouble actually serving the damn thing through nginx though. My config is:

> server {
>     listen 80;
>     listen       [::]:80 default_server;
> 	server_name [redacted];
> 
>     # CHANGE THIS to match your web root where the project is installed
>     root /var/www/html/;
>     index index.php index.html index.htm;
> 
> 	# php info
>     location ~ \.php$ {
>         fastcgi_split_path_info ^(.+\.php)(/.+)$;
> 
>         # if you are using php5-fpm uncomment this next line
>         # fastcgi_pass unix:/var/run/php5-fpm.sock;
>         # if you are using fastcgi on loopback uncomment this next line
>         # fastcgi_pass 127.0.0.1:9000;
> 
>         fastcgi_index index.php;
>         include fastcgi_params;
>         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
>     }
> 
> 	# CHANGE THIS to be where your attachments are stored.
>     location /attachments {
>         internal;
>         alias /var/www/html/storage/app/attachments;
>     }
> 
>     location / {
>         try_files /public/$uri /public/$uri/ /public/index.php$is_args$args;
>     }
> }

**Comment by hawkoon** [comment]
Ok found the solution (php-fpm wasn't running). Had to deal with a bunch more permission errors and voila, it seems to be working!
![success](https://user-images.githubusercontent.com/54553501/78459536-f8000680-76b9-11ea-997b-cb994bfe31e6.png)

**Comment by hawkoon** [comment]
Haha spoke too soon. Posting doesn't work
![error1](https://user-images.githubusercontent.com/54553501/78459582-53ca8f80-76ba-11ea-87e3-8e5259a7cdca.png)
![error2](https://user-images.githubusercontent.com/54553501/78459586-562ce980-76ba-11ea-9811-cb06352a8de6.png)

 (getting a blank error) and the captcha also seems broken. @jaw-sh

**Comment by hawkoon** [comment]
Fixed some permissions and now getting this error when trying to post a thread:
`Undefined index: reply_to (View: /var/www/html/resources/views/content/board/post/single/container.blade.php)`
Captcha is also still broken.

**Comment by hawkoon** [comment]
Ok posting works all of a sudden (didn't change anything) and even though the captcha looks weird (sometimes only 3 characters) that works too.

**Comment by hawkoon** [comment]
Ok new bug. Trying to post while logged in and with capcode gives: `instanceof expects an object instance, constant given`
@jaw-sh

**Comment by hawkoon** [comment]
@jaw-sh

**Comment by jaw-sh** [comment]
```Infinity Next was never completed and is currently in an unusable state. I am currently working on refactoring it to Laravel 6 and modernizing some backend work, but it is just something I am doing for myself. For some reason, I just can't stand to see it unfinished.

Use at your own risk: I can't help you.```

You don't get to demand my attention dude, and I'm not walking you through setting up nginx and installing php-fpm modules.

**Comment by hawkoon** [comment]
> > Infinity Next was never completed and is currently in an unusable state. I am currently working on refactoring it to Laravel 6 and modernizing some backend work, but it is just something I am doing for myself. For some reason, I just can't stand to see it unfinished.
> > Use at your own risk: I can't help you.
> 
> You don't get to demand my attention dude, and I'm not walking you through setting up nginx and installing php-fpm modules.

Maybe actually write functional, decent working code before even publishing it on Github.
