### ISSUE TITLE
Anonymous users should share functions with the User model.

### ISSUE THREAD

**Issue by jaw-sh** [infinity-next/infinity-next#30]
`Auth::user()` currently returns a `\App\User` if the user is authenticated. I have organized the controller structure so that `MainController` inherits `Controller` and automatically binds authentication to every page on the application. All other controllers either directly inherit `MainController`, or (in the Auth controllers), inherits a controller which inherits `MainController`.

What would improve this system is an Anonymous user. If a user is not authenticated, there is no model which exists to pose challenges against. By splitting out permission challenges into a new `trait` and implementing it both on the `\App\User` and another, non-inherited class, we can easily share logic between the two and yield reliable information.

**Comment by ctrlcctrlv** [comment]
This is especially important because 99% of people will never log in.
