### ISSUE TITLE
Create ad space

### ISSUE THREAD

**Issue by jaw-sh** [infinity-next/infinity-next#31]
Copypaste has 2 300x250 ads and 1 720x90 ad. Find some room in our default template for this.

**Comment by ctrlcctrlv** [comment]
Typically boards also have an announcement space as well. Top ad normally goes above the post form but below the global announcement.

Then the blotter goes under the post form in red.

**Comment by jaw-sh** [comment]
1920x
http://i.imgur.com/OtsN19V.png

768x
http://i.imgur.com/lf8cAMV.png
