### ISSUE TITLE
nntpchan integration

### ISSUE THREAD

**Issue by majestrate** [infinity-next/infinity-next#41]
infinity-next should implement srnd integration so that it can act as a frontened for nntp-overchan.

right now i am working on stubs for this in srnd in the event that upstream cares to merge this functionality in.

**Comment by jaw-sh** [comment]
@majestrate Can you give a little more detail as to what this involves? I don't actually have a clue what this issue is going to add, why we want to support this specific 3rd party software, or how it's going to affect or encumber long-term development.

**Comment by majestrate** [comment]
the full overchan spec is located [here](http://anonet2.biz/Overchan.html) as one page if you want your brain to explode.
> Overchan is a newsgroup meant to be served on web frontends in an effort to create a decentralized imageboard. Moderation takes place on each frontend itself. Message and image transport is using MIME multipart messages and Base64 as encoding for Images. All messages need to be valid NNTP messages, the transport of messages need to follow NNTP specifications. It is possible to use an existing NNTP daemon like INN or to implement the NNTP sync part as well.

nntpchan (aka nntp-overchan / overchan ) is a decentralized nntp (usenet) based pastebin/imageboard/forum that was written and deployed about 2 years ago. the software stack that was originally used is in a similar condition that infinity is, hence I am rewriting the nntpchan software stack. the software stack contains 2 components, the frontend software and the nntp daemon (srnd - some random news daemon) . there is a bidirectional line of communication between frontend and nntp daemon, when the frontend gets a post, it regenerates markup forwards it to the daemon and the daemon federates the post to all nntp daemons it is peered with. when the nntp daemon gets a post from another nntp daemon, it sends it to everyone else in their peering that doesn't have it (and to those whol will accept the post) and forwards it to the frontend, and the frontend regenerates the markup. included in this stack is a cryptographically signed moderation system in which admins of each node whitelist trusted keys to allow remote or local moderators to moderate posts.

As far as I can tell, any program that can access the same database as infinity-next would be able to "inject" posts into the database and as a result would allow posting without using http (is that correct?) What I want to do is have the nntpchan nntpd daemon be able to share the same backend as infinity-next, providing the nntp federation functionality of nntpchan while using infinity-next as a dynamic php based "frontend" for nntpchan.

What needs to be added to infinity-next is relatively trivial: 

* a hook that infinity-next can call to tell srnd "we got a post from someone using our frontend, this is their info you need to get it from the database"
* a hook that srnd can call to tell infinity-next "we got a new post from $place and we put the post in the database"

cc @ctrlcctrlv

**Comment by jaw-sh** [comment]
This work sounds like it's a part of a larger API system. I'm not adverse to the idea but it should be done as part of a larger, carefully planned structure. Something that can be stringently documented, like Twitter's API with PUTs/GETs and expected input.

**Comment by jaw-sh** [comment]
Issue author will need to build his program to use our API after it is built.
