### ISSUE TITLE
Allow image upload from URL

### ISSUE THREAD

**Issue by jadedgnome** [infinity-next/infinity-next#43]
add file from url,  limit to one url at a time.

**Comment by jaw-sh** [comment]
This is doable.

Note: This should be a config option. Downloading a file from a site opens up a server to an IP Identification attack.

**Comment by ctrlcctrlv** [comment]
If you add this it must be disabled on 8chan.

Perhaps it can be allowed for some trusted hosts only, like pomf.se, imgur, et cetera.

**Comment by jadedgnome** [comment]
@ctrlcctrlv 
I agree, adding trusted hosts is a safer solution.

**Comment by anonfagola** [comment]
i'll do this and make it a config option with an array of trusted hosts

**Comment by lulalala** [comment]
Just curious how is an IP attack performed?

**Comment by jaw-sh** [comment]
@lulalala You upload an image to a webserver that logs requests and then issue a command to the foreign service to upload an image from URL. Once the request is made, your webserver logs will show the request and its origin IP. The IP can then be used for direct DDoS attacks that bypass Cloudflare on a poorly configured server.
