### ISSUE TITLE
Redirect Vichan-style Routes

### ISSUE THREAD

**Issue by jaw-sh** [infinity-next/infinity-next#46]
The following route styles need to be handled.

* [x] `/operate/res/20692.html`  
* [x] `/operate/res/20692+50.html`
* [x] `/operate/index.html`
* [x] `/operate/2.html`

Additionally, copypaste uses these for unique features.
* [x] `/_g/`
* [x] `/_t/`

/_g/ and /_t/ are text files. I'm not going to route those. He can upload them to `public` on his own and they should continue to exist. In the future, we can probably have a URI like `/board/post/post_id` for GPG signatures. /_t/ will remain as-is because it's not an imageboard feature.

**Comment by ctrlcctrlv** [comment]
The only unique directories are:
`_g`: GPG signed messages.
`_t`: Monthly ransparency messages.
