### ISSUE TITLE
Database seeder unable to add options with default value of null

### ISSUE THREAD

**Issue by tunayuyar** [infinity-next/infinity-next#57]
Hi 

I dont know if you care about installation problem on windows but Im getting this error on:

C:\Domains\beta>php artisan db:seed
Seeding admin user.
[Illuminate\Database\QueryException]
SQLSTATE[HY000]: General error: 1364 Field 'username' doesn't have a default value (SQL: insert into `users` (`user_id`, `updated_at`, `created_at`) values (1, 2015-06-17 15:09:54, 2015-06-17 15:09:54))
[PDOException]
SQLSTATE[HY000]: General error: 1364 Field 'username' doesn't have a default value
C:\Domains\beta>

Server:
Windows Server 2012 R2
IIS 8.5 
PHP 5.6
MYSQL server 5.6

**Comment by tunayuyar** [comment]
![sql](https://cloud.githubusercontent.com/assets/4925001/8226199/2f6f597a-15a5-11e5-930e-92a9db5957b6.png)

After issuing this commands and doing php artisan db:seed every time after issuing, Im getting SQLSTATE23000 : Integrity constraint violation: 1048 column 'default_value' cannot be null.

Maybe this helps.

**Comment by jaw-sh** [comment]
Hey, I'll address this today.

The DB seeder falls out of date a lot because I'm constantly adding new stuff to the database and I only need to set up a new db once every 2 weeks.

I know exactly what's wrong with this, though.

**Comment by jaw-sh** [comment]
@tunayuyar Hey, I went back and changed a migration file (bad practice, but it should be fine since nobody's really following development) to fix this. I must have made a DB change at some point and failed to document it.

Just drop your tables and try again.

I see unrelated errors in your Workbench log, btw. Are those related to the seeder?

**Comment by tunayuyar** [comment]
Errors are just me writing column names wrong. 

Tried fresh install(deleted directory, new git, dropped db new db) still getting error:


C:\Domains\beta>php artisan migrate
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2015_04_21_190853_create_boards_table
Migrated: 2015_04_21_201843_create_posts_table
Migrated: 2015_04_24_095424_add_cashier_columns
Migrated: 2015_04_29_042521_create_stripe_charge_table
Migrated: 2015_05_11_025616_create_file_table
Migrated: 2015_05_13_095544_create_permission_tables
Migrated: 2015_05_13_102216_create_role_table
Migrated: 2015_05_13_102931_create_role_pivots
Migrated: 2015_05_15_215910_create_permissions_cache
Migrated: 2015_05_16_233934_post_features
Migrated: 2015_05_18_053308_create_bans
Migrated: 2015_05_20_142209_create_public_log
Migrated: 2015_05_22_074031_create_site_config
Migrated: 2015_05_22_182057_create_option_groups
Migrated: 2015_05_22_184424_create_option_group_assignments
Migrated: 2015_05_29_020017_add_cache_support
Migrated: 2015_05_31_184655_create_session_table
Migrated: 2015_05_31_184710_options_mutator
Migrated: 2015_06_12_181054_password_legacy

C:\Domains\beta>php artisan db:seed
Seeding admin user.
  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1364 Field 'username' doesn't have a default value (SQL: insert into `users` (`user_id`, `updated_at`, `created_at`) values (1, 2015-06-18 21:39:32, 2015-06-18 21:39:32))
  [PDOException]
SQLSTATE[HY000]: General error: 1364 Field 'username' doesn't have a default value

I suppose error is related with mysql config, strict option. After using this advice(http://stackoverflow.com/questions/18751291/mysql-error-1364-field-display-name-doesnt-have-default-value)  SET GLOBAL sql_mode=''   php artisan db:seed worked flawlessly.

BUT now after Admin password created I cannot login. using "Admin" as username

I tried using:
1-all the words with spaces
2-all the words without spaces
3-words alone

None of them seem to work. What am I doing wrong?

**Comment by jaw-sh** [comment]
For some reason, with your code, `firstOrCreate` is creating an item with only the key it's looking for. I know copypaste also had a similar issue, but I reverted the change because I didn't find a reason behind it.

I'm committing another fix, let me know if this works. Same deal, drop all tables. @tunayuyar

**Comment by tunayuyar** [comment]
Still I cannot login with the given password. If you have free time I can provide links and password just come to my irc server, irc.eksichat.com channel #eksichat my nick is saiko

**Comment by tunayuyar** [comment]
LOL, I suppose it was my mistake.  No problems about login.

For the future installations on windows please note:

Execute SET GLOBAL sql_mode='' before db:seed and everything will be fine after Josh's last fix.
