### ISSUE TITLE
APP_KEY length is dependant on cipher (default MCRYPT_RIJNDAEL_128)

### ISSUE THREAD

**Issue by Kentaa** [infinity-next/infinity-next#58]
The APP_KEY variable in .env must be a fixed length depending on the cipher used, the default is MCRYPT_RIJNDAEL_128. I'd recommend automatically generating a binary key of the appropriate length instead of having the user supply a potentially bad or invalid key.

From PHP.net:

Version | Description
---------- | ----------
5.6.0 | Invalid key and iv sizes are no longer accepted. mcrypt_encrypt() will now throw a warning and return FALSE if the inputs are invalid. Previously keys and IVs were padded with '\0' bytes to the next valid size.

Illuminate\Encryption doesn't have a sanity check for this, so PHP versions before 5.6.0 will accept bad keys like "hunter2" which have low entropy.

**Comment by tunayuyar** [comment]
Well I got error(can not view website) with supplying 12 character length key. Then using this command php artisan key:generate, I suppose laravel solved itself.

**Comment by jaw-sh** [comment]
@tunayuyar That sounds like the correct solution. I'll set that as a step in the installation guide.

**Comment by jaw-sh** [comment]
@Kentaa I've inserted a step between `migrate` and `db:seed` that calls for `key:generate`. Can you please reinstall and confirm if that fixes the issue on your version of PHP?

**Comment by Kentaa** [comment]
Yes, `php artisan key:generate` generates a proper length key in .env.

**Comment by jaw-sh** [comment]
Sweet, thank-you for the report.
