### ISSUE TITLE
Implement better captcha

### ISSUE THREAD

**Issue by Kentaa** [infinity-next/infinity-next#60]
The current captcha is weak and could be read by a computer.

Accessing any pages with a captcha will invalidate all captchas on other open pages because the request overwrites the old value.

The same captcha can be re-used multiple times. This works because the captcha's code is only set when /cp/captcha is accessed, and past captchas are not invalidated.

I included these three issues together because a solution will likely solve them all at the same time. I hope this is the correct way to go about it.

**Comment by jaw-sh** [comment]
If you are intending on resolving this yourself, can you please explain what you will do to correct the problem?

**Comment by Kentaa** [comment]
The easiest solution would to be use reCAPTCHA or similar, but there may be reasons to avoid external services when possible.

The PHP Imagick documentation is spotty, so I haven't figured out how to get distortions to resize dynamically (if that's even possible?). Without being able to use distortions I'm not sure the captcha I came up with is any good. I've got 6 samples here:
![Uploading captcha_attempt_000.png…]()

For captcha invalidation and re-use, Include a hidden field in any form with a captcha which has the captcha's code and a timestamp encrypted or HMAC'd. The timestamp will allow the captcha to expire after a set length of time. When a captcha is entered correctly, store it along with the timestamp to prevent re-use of the same captcha. After the stored captcha has expired, it can be deleted.

I think this is a good solution, but I do want input in case I've overlooked something important.

**Comment by Kentaa** [comment]
Oops, I closed the issue by mistake when trying to upload an image, sorry about that.

The easiest solution would to be use reCAPTCHA or similar, but there may be reasons to avoid external services when possible.

The PHP Imagick documentation is spotty, so I haven't figured out how to get distortions to resize dynamically (if that's even possible?). Without being able to use distortions I'm not sure the captcha I came up with is any good. I've got 6 samples here:
![Uploading captcha_attempt_000.png…]()

For captcha invalidation and re-use, Include a hidden field in any form with a captcha which has the captcha's code and a timestamp encrypted or HMAC'd. The timestamp will allow the captcha to expire after a set length of time. When a captcha is entered correctly, store it along with the timestamp to prevent re-use of the same captcha. After the stored captcha has expired, it can be deleted.

I think this is a good solution, but I do want input in case I've overlooked something important.

**Comment by Kentaa** [comment]
I've made the above with a different style of captcha using waves to distort the letters. This adds a new dependency for php-imagick and [Laravel scheduling](http://laravel.com/docs/master/scheduling) must be configured on the server to prune old captchas from the database. The captcha itself can be changed if it is too hard for humans or too easy for computers.

https://github.com/Kentaa/infinity-next

I haven't used Laravel before, so I don't know if I've done everything correctly.

**Comment by jaw-sh** [comment]
I cannot require people to use Imagick because of the nature of the software. Please write your code so that it degrades gracefully without the library.

**Comment by Kentaa** [comment]
I will try to create another captcha using php-gd. If needed the [current captcha](https://github.com/Kentaa/infinity-next/blob/master/app/Support/CaptchaBisque.php#L31-L112) can be junked for something using only php-gd.

The code I'm not sure about being correct for Laravel: https://github.com/Kentaa/infinity-next/blob/master/app/Support/CaptchaBisque.php#L127-L135

**Comment by jaw-sh** [comment]
Nah mate, you're doing a lot of things incorrectly.

1. Do not ever use raw SQL. We're supporting multiple database formats and the only way to do that is by using the Laravel Eloquent class. Review (http://laravel.com/docs/5.0/eloquent)[Eloquent]. Every DB table needs an Eloquent model (in this case, App/Captcha), and it must be used to deal with insertions / counts, etc.
2. Don't do heavy logic within `if ()`. If you're doing so much you have to split the `if ()` into multiple lines, that logic should be done outside of the `if ()`.
3. Allman brackets.

```
for ($i  = 0; $i < 1; ++$i)
{
	echo "Ayyyy."
}
```

Also, as an aside, and I don't know any details about this: There is a module we have called InterventionImage that should handle both GD and Imagick based on config (e.g. is a contract similar to the database agnostic system, but for image libraries). Is there any reason why we can't use that? It's already a part of the project.

**Comment by jaw-sh** [comment]
And sorry if I sound like I'm being a picky douche, but I have to be. I'm trying to hold everyone who'd like to contribute to the same standards as Laravel, and that means having to be a douche sometimes. A lot of these practices aren't native to me either, I've had to learn along the way, and even I still slip up -- but it's for a good cause.

**Comment by Kentaa** [comment]
I understand how it is with code quality.

I looked at InterventionImage but it seems to only support features which exist in both php-gd and php-imagick, so I couldn't use it for what I had planned.

**Comment by jaw-sh** [comment]
>I looked at InterventionImage but it seems to only support features which exist in both php-gd and php-imagick, so I couldn't use it for what I had planned.
Ah okay, thank you for doing that.

Can you use II for everything _but_ the things specific to Imagick? I'm unfamiliar with image manipulation in PHP, so I'm curious if you can do something like:

````
$Image = new InterventionImage();

$Image->obscurify();

if ($Image->object instanceof Imagick)
{
	$Image->object->specialObscurify();
}
``

If that makes sense...

**Comment by tunayuyar** [comment]
About captcha, is it possible to add option to disable it completely?

**Comment by jaw-sh** [comment]
@tunayuyar, the appropriate way to do that would be to make a config option for "post without captcha" and then set it to "Allow" for the Anonymous group. I'll do this as a part of my recent work.

**Comment by Kentaa** [comment]
A few samples of the php-gd captcha I'm working on:
![gd_000_samples](https://cloud.githubusercontent.com/assets/4675002/8314679/03d70124-19b9-11e5-90eb-7b330d12bf6d.png)

And this is the current iteration of the php-imagick captcha:
![imagick_005_samples](https://cloud.githubusercontent.com/assets/4675002/8314690/1140307e-19b9-11e5-8647-0d9fb4b7e43c.png)

**Comment by jaw-sh** [comment]
@Kentaa A bit odd to throw back to this issue, but I recently told copypaste he should use his knowledge of computer screen readers and custom fonts to build us a better captcha system. When he's done working on the self-serve for 8ch, I think this would be a good task for him. I don't know if you ever got any work on this done yourself, but do know I'm aware of the problems you've outlined and I intend on resolving them soon.

**Comment by Kentaa** [comment]
The code I wrote solves the issues, but I don't know if it holds up to the code standard. Feel free to strip it for parts if needed.

**Comment by jaw-sh** [comment]
Did you ever submit a pull request? I don't remember ever looking at code

**Comment by Kentaa** [comment]
I didn't do a pull request since I don't know if my code is the best/correct way to do things.

Right now the captcha is rendered with each page and authenticated using HMAC, so it would slow page load times depending on how long the captcha takes to render. This can be avoided by either storing all captchas in the database (a bad idea) or using authenticated encryption instead of the current HMAC method. This will allow rendering the captcha independent of the page.

**Comment by Kentaa** [comment]
Just noticed the edit. Yes, php-imagick is an optional dependency now, and falls back to php-gd if not available.
