### ISSUE TITLE
Username and Email are not mutually exclusive

### ISSUE THREAD

**Issue by Kentaa** [infinity-next/infinity-next#62]
The Username and Email of a user are not mutually exclusive. A new user can register with a username matching an existing user's email address.

User A:
Username: foo
Email: foo@example.com

User B:
Username: foo@example.com
Email: bar@example.com

This may cause unwanted behaviour as the Username and Email are both used to login.

**Comment by jaw-sh** [comment]
New restrictions should prevent this. Even if for some reason an email is alphanumeic (it won't ever be), there is an explicit check to make sure this never happens.
