### ISSUE TITLE
Board URI route and normalisation

### ISSUE THREAD

**Issue by Kentaa** [infinity-next/infinity-next#63]
It is currently possible to create boards with URIs which don't match the route. ex. ``/foo1/`` and ``/täst/`` can be created, but the route doesn't match so they return 404.

However, täst can be accessed as ``/tast/`` due to the database (MySQL on my testing server) using utf8_unicode_ci. This means tEsT and test, täst and tast, and straße and strasse are interchangeable.

The board URI isn't properly normalised if it contains non-ASCII characters. ex. TÄST gets normalised as tÄst.

**Comment by jaw-sh** [comment]
Okay, this should be fixed. I again went the easy route and limited it to alphanumeric. The RegEx used to validate a board uri is now shared between the creation form and the router.

I also found a bug that let you make boards twice ... oops.

Good report, thank you.
