### ISSUE TITLE
failure to seed database when using sqlite

### ISSUE THREAD

**Issue by majestrate** [infinity-next/infinity-next#86]
ran

    ./artisan migrate

runs fine

then ran

    ./artisan db:seed

    Seeding admin user.
    User "Admin" has been created with the following password:
    lazy cheap hairy key
    Seeded: UserSeeder
    Seeding boards.
    Success. Board exists now. Accessible at /test/.
    Seeded: BoardSeeder
    Seeding permissions.
    Done. Seeded 37 new permission(s).
    Seeded: PermissionSeeder
    Seeding permission groups and relationships.

    [Illuminate\Database\QueryException] 
    SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed:
    permission_groups.display_order (SQL: insert into "permission_groups" ("group_name", "is_system_only", "is_account_only") values (board_controls, 0, 0))

    [PDOException]                                                                                                   
    SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: permission_groups.display_order

**Comment by jaw-sh** [comment]
Replicated. Thanks for testing SQLite. I haven't had anyone do this yet copypaste runs on PostgreSQL and I use MySQL because I'm a scrub.

**Comment by jaw-sh** [comment]
Okay, this needs more work than I was expecting. I resolved the initial error, but there's no SQLite equivalent of enum, which we use for exactly one table.

I really want to support SQLite because I want to support shared hosts and cheap Hidden Services, so I'll have to change the enum column to string and move the responsibility of data integrity to the model in PHP.

**Comment by jaw-sh** [comment]
There are actually 4 columns in 2 tables that use enum. As follows:

options.format, options.data_type, options.option_type and  
board_assets.asset_type

I've replaced these with string,24 and have set up mutators for these values in their model that would throw exceptions similar to this if you attempt to assign them an invalid value.

```
[Exception]
App\Option::setFormatAttribute - "asdasdsadas" not in psuedo-enum array [textbox,spinbox,onoff,onoff,textbox,radio,select,checkbox,template,callback]                                                  
```

I'll have this finished and tested locally in the hour.

**Comment by jaw-sh** [comment]
@majestrate I've gotten SQLite working locally. If you find any other database errors let me know.

**Comment by jaw-sh** [comment]
@majestrate has verified this is now working.
